### ISSUE TITLE
[Recommendation]: Use this Vue 3.x plugin to add Nativescript-Vue-Web support

### ISSUE THREAD

**Issue by eladcandroid** [Nativescript-Vue-Web/Nativescript-Vue-Web#143]
https://github.com/jawa-the-hutt/vue-cli-plugin-nativescript-vue

**Comment by yerol** [comment]
@eladcandroid Thanks for your comment. We are actively involved in testing and development of this plugin. In fact, NVW is already integrated with this plugin and can only work with the tooling provided by it. We will be announcing this soon. Please bear with us.
